services:

  postgres:
    image: postgres:15
    container_name: realtime_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtime
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  realtime_dbt:
    build: .
    container_name: realtime_dbt
    depends_on:
      - postgres
    volumes:
      - ./realtime:/usr/app
    ports:
      - "8080:8080"

  spark:
    image: apache/spark:3.5.1
    container_name: realtime_spark
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark:/opt/spark-apps
      - ./bronze:/bronze
    depends_on:
      - postgres

volumes:
  postgres_data:
